security:
    providers:
        user_provider:
            id: App\Security\Core\User\KeycloakUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api/
            context: shared
            guard:
                authenticators:
                    - App\Security\Guard\KeycloakApiAuthenticator

        main:
            context: shared
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\Guard\KeycloakAuthenticator
            logout:
                path: app_logout
                target: ext_home
                success_handler: App\Security\Http\Logout\KeycloakLogoutSuccessHandler